#name, main, version and api are required
name: PocketLink
main: me.Mark.pocketLink.PocketLink
#remember version and api is string, don't write it like this: 1.0.0, or there will be an exception
version: "1.0.0"
api: ["1.0.0"]

load: POSTWORLD
author: Mark
description: Pocket Link
website: N/A
commands:
  example:
    description: Example command
    usage: "/example"
    permission: exampleplugin.command.example
permissions:
  exampleplugin.command.example:
    description: "Allows the user to run the example command"
    default: true